# Generated by Django 5.1 on 2024-09-17 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='type_id',
            field=models.CharField(choices=[('TI', 'Tipo de identificación'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=20),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('TI', 'Tipo de identificación'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=10)),
                ('identification', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('date_birth', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.CharField(max_length=100)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
