# Generated by Django 5.1 on 2024-09-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_administrador_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL),
        ),
    ]
