# Generated by Django 5.1 on 2024-11-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_register', models.DateField()),
                ('Peso_corporal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IMC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Porcentaje_grasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Porcentaje_musculo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Porcentaje_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hombros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pectoral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('biceps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Espalda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cintura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cadera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gluteos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pierna', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pantorrilla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='mainapp.cliente')),
            ],
        ),
    ]
