# Generated by Django 5.1 on 2024-11-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_evolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolucion',
            old_name='Cadera',
            new_name='cadera',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Cintura',
            new_name='cintura',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Espalda',
            new_name='espalda',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Estatura',
            new_name='estatura',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='IMC',
            new_name='imc',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Pierna',
            new_name='pierna',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Porcentaje_agua',
            new_name='porcentaje_agua',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Porcentaje_grasa',
            new_name='porcentaje_grasa',
        ),
        migrations.RenameField(
            model_name='evolucion',
            old_name='Porcentaje_musculo',
            new_name='porcentaje_musculo',
        ),
    ]
