# Generated by Django 5.1 on 2024-11-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_cadera_evolucion_cadera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolucion',
            old_name='Peso_corporal',
            new_name='peso_corporal',
        ),
    ]
