# Generated by Django 5.1 on 2024-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_peso_corporal_evolucion_peso_corporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucion',
            name='date_register',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
