# Generated by Django 5.1 on 2024-11-04 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_evolucion_identification_evolucion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucion',
            name='biceps',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='cadera',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='cintura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='espalda',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='gluteos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='hombros',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='identification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='pantorrilla',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='pectoral',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='peso_corporal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='pierna',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='porcentaje_agua',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='porcentaje_grasa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='porcentaje_musculo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type_reserve', models.CharField(choices=[('R', 'Reserva'), ('M', 'Membresía')], max_length=50)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('date_reserve', models.DateField()),
                ('time_reserve', models.TimeField()),
                ('phone', models.CharField(max_length=15)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mainapp.cliente')),
            ],
        ),
    ]
