# Generated by Django 5.1 on 2024-11-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_evolucion_biceps_alter_evolucion_cadera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='type_reserve',
            field=models.CharField(choices=[('E', 'Entrenamiento personal'), ('M', 'Membresía'), ('S', 'Spa')], max_length=50),
        ),
    ]
